
package services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonaWS", targetNamespace = "http://ejb.said.com/", wsdlLocation = "http://localhost:8080/PersonaWS/PersonaWS?wsdl")
public class PersonaWS_Service
    extends Service
{

    private final static URL PERSONAWS_WSDL_LOCATION;
    private final static WebServiceException PERSONAWS_EXCEPTION;
    private final static QName PERSONAWS_QNAME = new QName("http://ejb.said.com/", "PersonaWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PersonaWS/PersonaWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONAWS_WSDL_LOCATION = url;
        PERSONAWS_EXCEPTION = e;
    }

    public PersonaWS_Service() {
        super(__getWsdlLocation(), PERSONAWS_QNAME);
    }

    public PersonaWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONAWS_QNAME, features);
    }

    public PersonaWS_Service(URL wsdlLocation) {
        super(wsdlLocation, PERSONAWS_QNAME);
    }

    public PersonaWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONAWS_QNAME, features);
    }

    public PersonaWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonaWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonaWS
     */
    @WebEndpoint(name = "PersonaWSPort")
    public PersonaWS getPersonaWSPort() {
        return super.getPort(new QName("http://ejb.said.com/", "PersonaWSPort"), PersonaWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonaWS
     */
    @WebEndpoint(name = "PersonaWSPort")
    public PersonaWS getPersonaWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ejb.said.com/", "PersonaWSPort"), PersonaWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONAWS_EXCEPTION!= null) {
            throw PERSONAWS_EXCEPTION;
        }
        return PERSONAWS_WSDL_LOCATION;
    }

}
