
package services;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonaWS", targetNamespace = "http://ejb.said.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonaWS {


    /**
     * 
     * @param id
     * @return
     *     returns services.Persona
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "find", targetNamespace = "http://ejb.said.com/", className = "services.Find")
    @ResponseWrapper(localName = "findResponse", targetNamespace = "http://ejb.said.com/", className = "services.FindResponse")
    @Action(input = "http://ejb.said.com/PersonaWS/findRequest", output = "http://ejb.said.com/PersonaWS/findResponse")
    public Persona find(
        @WebParam(name = "id", targetNamespace = "")
        Object id);

    /**
     * 
     * @param persona
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "create", targetNamespace = "http://ejb.said.com/", className = "services.Create")
    @Action(input = "http://ejb.said.com/PersonaWS/create")
    public void create(
        @WebParam(name = "persona", targetNamespace = "")
        Persona persona);

    /**
     * 
     * @return
     *     returns java.util.List<services.Persona>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://ejb.said.com/", className = "services.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://ejb.said.com/", className = "services.FindAllResponse")
    @Action(input = "http://ejb.said.com/PersonaWS/findAllRequest", output = "http://ejb.said.com/PersonaWS/findAllResponse")
    public List<Persona> findAll();

}
